Added my name{Nazmul6180}
zero-to-mastery/start-here-guidelines pull request #16677
Opened 2022-09-08 09:36 UTC by Nazmul6180

i have added my name to the contributor list. @aneagoie

2022-09-08 16:15 UTC, nuhmanpk approved these changes

2022-09-16 13:15 UTC, sophiabrandt requested changes

2022-09-16 13:15 UTC, sophiabrandt commented on CONTRIBUTORS.md
> + Nazmul
Please remove this line.

2022-09-16 13:15 UTC, sophiabrandt commented on CONTRIBUTORS.md
> + master
Please remove this line.

2022-10-02 07:07 UTC, merged