added my name to contributor list
zero-to-mastery/start-here-guidelines pull request #22484
Opened 2024-05-24 05:45 UTC by db1830

I've added my name to the list.@db1830

2024-05-24 12:13 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-05-24 12:13 UTC, StackOverflowIsBetterThanAnyAI commented on CONTRIBUTORS.md
> +-[@db1830](https://github.com/db1830)
Correct markdown syntax:
```suggestion
- [@db1830](https://github.com/db1830)
```

2024-05-25 07:59 UTC, StackOverflowIsBetterThanAnyAI approved these changes

2024-05-25 08:15 UTC, db1830 reviewed
Contributor.md

2024-05-25 08:57 UTC, closed without merging