Added myself to contributor's list
zero-to-mastery/start-here-guidelines pull request #22502
Opened 2024-05-29 17:15 UTC by rewpolo

2024-05-29 17:34 UTC, rewpolo commented
I ran git pull master origin and recommitted

2024-05-31 15:31 UTC, shreeentka commented on CONTRIBUTORS.md
> +\_ [Ramon R](https://github.com/artboycat)
I think you have mistake regarding writing your name in contributor list, you need use "-" this character while writing your name and use "\" character
![Screenshot 2024-05-31 210044](https://github.com/zero-to-mastery/start-here-guidelines/assets/169292446/1e1a66f2-f77e-4983-8e53-c44c34380535)

2024-05-31 15:33 UTC, shreeentka requested changes

2024-05-31 15:33 UTC, shreeentka commented on CONTRIBUTORS.md
> +\_ [Ramon R](https://github.com/artboycat)
Make this changes or you can follow instructions

2024-06-17 06:55 UTC, merged