Newbranch
zero-to-mastery/start-here-guidelines pull request #22981
Opened 2024-10-31 07:10 UTC by vedpawar2254

2024-10-31 07:10 UTC, vedpawar2254 commented
Can you consider this for hactober2024

2024-10-31 14:48 UTC, l-white commented
@vedpawar2254 Thanks for your contribution; however, we do not accept changes to the README for this repository. Please feel free to either remove those changes or create a new branch with your name and link to your Github profile added to the Contributors.MD file.

2024-11-05 16:38 UTC, LaurelineP requested changes
Aloha, thanks for your contribution.
Please address the feedbacks :)

2024-11-05 16:38 UTC, LaurelineP commented on README.md
We do not accept currently README.md changes, please remove any changes

2024-11-05 16:38 UTC, LaurelineP commented on CONTRIBUTORS.md
## Keep the code consistency code style
- [ ] Please add a new line above your line changed to

2024-11-08 10:17 UTC, LaurelineP commented
Aloha @vedpawar2254 
For managing reasons: your PR will be closed tomorrow.
Your PR is opened for more than a weak without changes:
I will close the PR tomorow if not changes are applied.
- Please address the feedback

If this will be closed: you are more than welcome to do another PR ( acknowledging the current feedbacks )
:)

2024-11-09 10:49 UTC, closed without merging